spring:
  security:
    oauth2: 
      client:
        registration:
          github:
            client-id: Iv23lirxFU5pqKzBsnSh
            client-secret: af3f8fc89d5d3d6ccdb37ebe42ccc56be0fe3003
  data:
    cassandra:
      keyspace-name: main
      contact-points: localhost
      username: oGRLeJQczZGBJXZHDFusWQmb
      password: +WabaiZ6PNx+q7nhy+0oay3n_aoSqai.YJaXhS6J35Mlk71ZFg0ZZydX1-By2OWucKr9FYdf_8JSEH_SSDnw48SQg712XESEKD7GW9uU.g4utINYwjZ,uHKrTEpISZu,
      schema-action: RECREATE_DROP_UNUSED
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
astra.db:
  id: 556f35e4-efce-4c96-8bd9-6ee399358568
  region: us-east1
  keyspace: main
  application.token: AstraCS:oGRLeJQczZGBJXZHDFusWQmb:d4c7fdd0302d9f168fb50ec4c4abe8c242ce54ac97d51bc17188ab44f293ec43
datastax.astra:
  secure-connect-bundle: secure-connect.zip
